setwd("C:/Everything Else/Blackhat/R/Titanic")
mydata = read.csv("train.csv")
testdata = read.csv("test.csv")
glm.fit = glm(Survived~Pclass+Sex+Age+Fare, family = binomial, data = mydata)
summary(glm.fit)
glm.fit = glm(Survived~Pclass+Sex+Age, family = binomial, data = mydata)
summary(glm.fit)